Add help tinymce plugin
plone/plone.base pull request #42
Opened 2023-05-11 21:48 UTC by ewohnlich

TinyMCE comes with a `help` plugin by default. For some reason it is not included in the schema of baseline plugins though. Can we add it?

2023-05-11 21:48 UTC, mister-roboto commented
@ewohnlich thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-05-12 00:16 UTC, ewohnlich commented
@jenkins-plone-org please run jobs

2024-02-23 08:02 UTC, rber474 commented
I've have also found this. Push PR.

@jenkins-plone-org please run jobs

2024-02-23 09:29 UTC, petschki approved these changes

2024-02-23 09:33 UTC, petschki requested changes
For an existing installation this needs an upgrade step to re-read the configuration registra `profile-Products.CMFPlone:dependencies`

2024-02-26 13:01 UTC, petschki commented
merged in #59 ... upgrade step coming up...

2024-02-26 13:01 UTC, closed without merging